# LSC Evaluation Framework - Sample/Mock Data

- conversation_group_id: "conv_group_1"
  description: "conversation group description"

  turn_metrics:
    - "ragas:faithfulness"
    - "ragas:response_relevancy"
    - "ragas:context_precision_without_reference"
  
  turn_metrics_metadata: 
    "ragas:faithfulness": 
      threshold: 0.99
  conversation_metrics: []
  conversation_metrics_metadata: {}
  
  turns:
    - turn_id: 1
      query: "User query"
      response: "API response"
      contexts:
        - content: "Context 1"
        - content: "Context 2"
      expected_response: "Expected Response"

- conversation_group_id: "conv_group_2"
  description: "conversation group description"

  turn_metrics:
    - "ragas:context_recall"
    - "ragas:context_relevance" 
    - "ragas:context_precision_with_reference"
  
  turn_metrics_metadata: {}
  conversation_metrics: []
  conversation_metrics_metadata: {}
  
  turns:
    - turn_id: 1
      query: "User Query"
      response: "API Response"
      contexts:
        - content: "Context 1"
      expected_response: "Expected Response"

- conversation_group_id: "conv_group_3"
  description: "Answer correctness evaluation test"
  
  turn_metrics:
    - "custom:answer_correctness"
  
  turn_metrics_metadata: {}
  conversation_metrics: []
  conversation_metrics_metadata: {}
  
  turns:
    - turn_id: 1
      query: "What is the capital of France?"
      response: "The capital of France is Paris."
      contexts:
        - content: "Paris is the capital and most populous city of France."
      expected_response: "Paris"

- conversation_group_id: "conv_group_4"
  description: "RAG response evaluation test"
  
  turn_metrics:
    - "custom:rag_response_evaluation"
  
  turn_metrics_metadata: {}
  
  conversation_metrics:
    - "deepeval:conversation_completeness"
    - "deepeval:conversation_relevancy"
  
  conversation_metrics_metadata: {}
  
  turns:
    - turn_id: 1
      query: "What is Kubernetes and how does it help with container orchestration?"
      response: "Kubernetes is an open-source container orchestration platform that automates the deployment, scaling, and management of containerized applications."
      contexts:
        - content: "Kubernetes is a portable, extensible, open-source platform for managing containerized workloads and services, that facilitates both declarative configuration and automation."
      expected_response: "Kubernetes is a container orchestration system that helps manage containerized applications at scale."
    
    - turn_id: 2
      query: "How do you scale applications with Kubernetes?"
      response: "Kubernetes provides horizontal pod autoscaling and cluster autoscaling to handle varying workloads."
      contexts:
        - content: "Kubernetes can automatically scale applications based on CPU utilization, memory usage, or custom metrics."
      expected_response: "Kubernetes scales applications using autoscaling features based on resource metrics."
