name: Black

on:
  - push
  - pull_request

jobs:
  black:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Python version
        run: python --version
      - name: Install uv
        run: pip install --user uv
      - name: Install devel dependencies
        run: uv sync --group dev
      - name: Black version
        run: uv run black --version
      - name: Black check
        run: uv run black --check .
