name: Check dependencies

on:
  - push
  - pull_request

jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Check Python version
        run: python --version
      - name: Install uv
        run: pip install --user uv
      - name: uv version
        run: uv --version
      - name: Generate requirements.txt file
        run: uv export --format requirements-txt --output-file requirements.txt --no-hashes
      - name: List requirements.txt file
        run: cat requirements.txt
