name: Pyright

on:
  - push
  - pull_request

jobs:
  pyright:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    name: "Pyright"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Python version
        run: python --version
      - name: Install uv
        run: pip install --user uv
      - name: Install dependencies
        run: uv sync
      - name: Install devel dependencies
        run: uv sync --group dev
      - name: Run Pyright tests
        run: make pyright
