name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python version
        run: python --version
      - name: Install uv
        run: pip install --user uv
      - name: Install dependencies
        run: uv sync
      - name: Install devel dependencies
        run: uv sync --group dev
      - name: Run tests
        run: uv run python -m pytest tests --cov=src --cov-report term-missing
      - name: Run agent tests
        run: cd lsc_agent_eval && uv sync --group dev && uv run python -m pytest tests --cov=src --cov-report term-missing
